version: '3'
services:
  yolov8_fastapi:
    build: .
    restart: "always"
    volumes:
    - ./:/app
    working_dir: /app
    ports:
      - "8080:8080"
    command: uvicorn main:app --reload --host 127.0.0.1 --port 8080